version: '3'
services:
  db:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
volumes:
  dbdata:
